#!/usr/bin/env bash
set -euo pipefail

SRC_ROOT="${1:-/share/lab_crd/lab_crd/CLONEID/data/LTEEs}"
DEST_ROOT="${2:-./dev_data/raw}"
mkdir -p "${DEST_ROOT}"

cp -n "${SRC_ROOT}/HGC-27_A1_seed_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_A1_seed_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_A1_seed_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_A1_seed_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_C_A45_harvesT1_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_C_A45_harvesT1_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_C_A45_harvesT1_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_C_A45_harvesT1_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_G1_A8_harvesT2_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_G1_A8_harvesT2_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_G1_A8_harvesT2_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_G1_A8_harvesT2_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_P2_A4_harvesT7_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_P2_A4_harvesT7_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_P2_A4_harvesT7_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/HGC-27_P2_A4_harvesT7_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_C_A3_harvesT3_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_C_A3_harvesT3_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_C_A3_harvesT3_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_C_A3_harvesT3_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PIP-FUCCI_A6_seed_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PIP-FUCCI_A6_seed_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PIP-FUCCI_A6_seed_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PIP-FUCCI_A6_seed_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_pop7_4N_NLS_A2_seed_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_pop7_4N_NLS_A2_seed_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_pop7_4N_NLS_A2_seed_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_pop7_4N_NLS_A2_seed_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PQ1_A1_harvesT26_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PQ1_A1_harvesT26_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PQ1_A1_harvesT26_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/MDA-MB-231_PQ1_A1_harvesT26_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_A1_seed_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_A1_seed_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_A1_seed_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_A1_seed_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_P1_A5_harvesT1_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_P1_A5_harvesT1_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_P1_A5_harvesT1_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_P1_A5_harvesT1_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r2_GFP_A2_seedT2_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r2_GFP_A2_seedT2_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r2_GFP_A2_seedT2_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r2_GFP_A2_seedT2_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r3_A15exp_seedT1_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r3_A15exp_seedT1_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r3_A15exp_seedT1_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SNU-668_r3_A15exp_seedT1_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_2N_jq1_A4_seed_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_2N_jq1_A4_seed_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_2N_jq1_A4_seed_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_2N_jq1_A4_seed_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_H2B_A1_seed_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_H2B_A1_seed_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_H2B_A1_seed_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_H2B_A1_seed_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_A59_seed_JC_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_A59_seed_JC_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_A59_seed_JC_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_A59_seed_JC_10x_ph_tr.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_C_A4_seedT1_10x_ph_bl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_C_A4_seedT1_10x_ph_br.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_C_A4_seedT1_10x_ph_tl.tif" "${DEST_ROOT}/"
cp -n "${SRC_ROOT}/SUM-159_NLS_4N_C_A4_seedT1_10x_ph_tr.tif" "${DEST_ROOT}/"
